// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/inoth/toybox"
	"github.com/inoth/toybox-layout/internal/controller"
	"github.com/inoth/toybox-layout/internal/provider"
	"github.com/inoth/toybox-layout/internal/service"
)

// Injectors from wire.go:

func initApp(dir string) *toybox.ToyBox {
	configMate := provider.NewConfigMate(dir)
	helloService := service.NewHelloService()
	helloController := controller.NewHelloController(helloService)
	ginHttpServer := provider.NewHttpServer(helloController)
	toyBox := newApp(configMate, ginHttpServer)
	return toyBox
}
